### PR TITLE
Update FizzBuzz.java

### PR DESCRIPTION
**Pull request by ssta**
Java8ification - a bit more compact and (imo) readable (there might be other ways to arrange the conditionals to be even nicer)

### CODE REVIEW

**Comment by ssta** [comment]
Fixed dodgy import and moved the import to after the (infeasibly long) copyright notice

**Comment by shlomif** [comment]
Hi @ssta ! Thanks for your contrib. I'd rather not break backcompat with older java versions, but you can create a new FizzBuzz_java8.java file or similar. Thanks!

**Comment by shlomif** [comment]
@ssta : hi! Can this pull-req be closed for now to avoid clutter?

**Comment by shlomif** [comment]
Closing per the last comment and freenode msgs.

**Pull request closed without merging**
